"""empty message

Revision ID: ae3fb86d6eb9
Revises: a9c7a5baa37c
Create Date: 2023-07-18 13:49:47.958132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae3fb86d6eb9'
down_revision = 'a9c7a5baa37c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dates', schema=None) as batch_op:
        batch_op.drop_constraint('fk_dates_event_id_events', type_='foreignkey')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_dates_event_id_events', 'events', ['event_id'], ['id'])

    # ### end Alembic commands ###
